/* Generated by Phoenix Tuner X */
package frc.robot.leds;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CANdleConfiguration;
import com.ctre.phoenix6.configs.LEDConfigs;
import com.ctre.phoenix6.controls.SingleFadeAnimation;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.LossOfSignalBehaviorValue;
import com.ctre.phoenix6.signals.RGBWColor;
import com.ctre.phoenix6.signals.StripTypeValue;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Robot;
import frc.spectrumLib.Rio;
import frc.spectrumLib.SpectrumSubsystem;
import frc.spectrumLib.Telemetry;
import lombok.Getter;

/** Subsystem that controls an addressable LED strip using a CANdle. */
public class CANdleLeds extends SubsystemBase implements SpectrumSubsystem {
    @Getter private final CANdle CANdle;
    @Getter private final CANdleConfiguration CANdleConfig;

    @Getter private final int numLeds = 20;

    public CANdleLeds() {
        CANdle = new CANdle(1, new CANBus(Rio.CANIVORE));
        CANdleConfig =
                new CANdleConfiguration()
                        .withLED(
                                new LEDConfigs()
                                        .withStripType(StripTypeValue.RGB)
                                        .withBrightnessScalar(0.5)
                                        .withLossOfSignalBehavior(
                                                LossOfSignalBehaviorValue.DisableLEDs));
        CANdle.getConfigurator().apply(CANdleConfig);
        CANdle.setControl(
                new SingleFadeAnimation(0, 20)
                        .withColor(new RGBWColor(156, 11, 255, 0))
                        .withFrameRate(Hertz.of(100)));
        Robot.add(this);
        Telemetry.print("LED Subsystem Initialized: ");
    }

    @Override
    public void setupDefaultCommand() {
        LedStates.setDefaultCommand();
    }

    @Override
    public void setupStates() {
        LedStates.bindTriggers();
    }
}
