/* Generated by Phoenix Tuner X */
package frc.robot.leds;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.spectrumLib.Rio;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.SingleFadeAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDSubsystem extends SubsystemBase {
    private final CANdle m_candle = new CANdle(0, new CANBus(Rio.CANIVORE));

    private final SingleFadeAnimation m_slot0Animation = new SingleFadeAnimation(8, 20)
        .withSlot(0)
        .withColor(new RGBWColor(29, 183, 255, 0))
        .withFrameRate(Hertz.of(100));

    private final SingleFadeAnimation m_slot1Animation = new SingleFadeAnimation(0, 7)
        .withSlot(1)
        .withColor(new RGBWColor(156, 11, 255, 0))
        .withFrameRate(Hertz.of(100));

    private final SolidColor[] m_colors = new SolidColor[] {
    };

    public LEDSubsystem() {
        setDefaultCommand(updateLEDs());
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }
            m_candle.setControl(m_slot0Animation);
            m_candle.setControl(m_slot1Animation);
        });
    }
}
