name: Generate JavaDoc and deploy to GitHub Pages

on:
  push:
    branches:
       [ "main" ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build project and generate javadoc
        run: ./gradlew build javadoc

      - name: Copy reports
        run: |
           rm -rf build/docs/javadoc/reports
           mkdir -p build/docs/javadoc/reports
           cp -r build/reports/. build/docs/javadoc/reports/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
          force_orphan: true