# This is a basic workflow to build robot code.

name: CI

# Triggers on push to main, and on ANY pull request regardless of target branch.
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2025-24.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Check Java formatting (Spotless)
      - name: Check Java formatting (Spotless)
        run: ./gradlew spotlessCheck

      # Runs a single command using the runners shell
      - name: Compile and run tests on robot code
        run: ./gradlew build
