name: PR Checks

# Triggers on any pull request
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    container: wpilib/roborio-cross-ubuntu:2025-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      # Declares the repository safe and not under dubious ownership
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check Java formatting (Spotless)
        run: ./gradlew spotlessCheck

      - name: Compile, test, and analyze
        run: ./gradlew build
